config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  #  see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :placements, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create] do
      get :photos, on: :member
    end
  end

  root 'placements#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/placement.rb
class Placement < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_many :reviews, dependent: :destroy

  validates :title, :photos, :price, :address, presence: true
  validates :address, uniqueness: true

  mount_uploaders :photos, PlacementPhotoUploader

  def self.search(title)
    where('title LIKE ?', "%#{title}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  default_scope { order(created_at: :desc) }

  belongs_to :user
  belongs_to :placement

  validates :title, :content, presence: true

  delegate :name, to: :user, prefix: true

  mount_uploaders :photos, ReviewPhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8 }, allow_nil: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user

  helper_method :current_user

  private

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate_user
    unless current_user
      redirect_to login_url, notice: 'You need to Log In'
    end
  end
end

app/controllers/placements_controller.rb
class PlacementsController < ApplicationController
  skip_before_action :authenticate_user, only: [:index, :show]

  def index
    if params[:search] && params[:commit] == 'Search'
      @placements = Placement.search(params[:search][:title]).page params[:page]
    else
      @placements = Placement.all.page params[:page]
    end
  end

  def new
    @placement = Placement.new
  end

  def create
    @placement = Placement.new(placement_params)
    if @placement.save
      redirect_to placement_path(@placement), notice: 'Placement added'
    else
      render :new
    end
  end

  def show
    @placement = Placement.find(params[:id])
    @review = Review.new
  end

  private

  def placement_params
    params.require(:placement).permit(:title, :address, :description,
                                      :price, :photos_cache, {photos: []})
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_placement

  skip_before_action :authenticate_user, only: [:index, :photos]

  def index
    @reviews = @placement.reviews.page params[:page]
  end

  def new
    @review = Review.new
  end

  def create
    @review = @placement.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to placement_path(@placement), notice: 'Review added'
    else
      render :new
    end
  end

  def photos
    review = Review.find(params[:id])
    @photos = review.photos
  end

  private

  def set_placement
    @placement = Placement.find(params[:placement_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :placement_id, :user_id,
                                   {photos: []}, :photos_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_signed_in, except: :destroy
  
  skip_before_action :authenticate_user

  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user and user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Hello, #{user.name}."
    else
      flash.now.alert = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out'
  end

  private

  def check_signed_in
    redirect_to root_path if current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_signed_in, only: :new

  skip_before_action :authenticate_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome, #{@user.name}."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def check_signed_in
    redirect_to root_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/placement_helper.rb
module PlacementHelper
  def linkify_address(address)
    address.gsub /\s+/, ','
  end

  def placement_description(placement)
    placement.description != '' ? placement.description : 'No description'
  end
end

app/views/layouts/_nav_bar_top.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role='navigation'
  div.container
    div.navbar-header
      button.navbar-toggle { type='button' 
        data={toggle: 'collapse', target: '#navigation-top'} }
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      = link_to 'Share Placement', root_path, class: 'navbar-brand'
    div.collapse.navbar-collapse id='navigation-top'
      ul.nav.navbar-nav
        - if current_user
          li = link_to 'Add placement', new_placement_path,
                 data: { turbolinks: 'false' }
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li = link_to 'Log Out', logout_path, method: :delete,
               id: 'logout-btn'
        - else 
          li = link_to 'Log In', login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Share Placement
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    = stylesheet_link_tag 'normalize'
    = stylesheet_link_tag 'application',
      media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application',
      'data-turbolinks-track' => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api"\
      "/js?key=#{ENV['google_maps_api']}&libraries=places"
    = csrf_meta_tags

  body
    = render 'layouts/nav_bar_top'
    
    .container-fluid
      .row
        .col-md-10.col-md-offset-1
          = bootstrap_flash
          = yield

app/views/placements/_form.html.slim
= simple_form_for @placement, html: { multipart: true } do |f|
  = f.error_notification

  = f.input :title
  = f.input :address, placeholder: ''
  = f.input :description
  - if @placement.photos?
    - @placement.photos.each do |photo|
      = image_tag photo.url, size: '50',
        class: 'img-thumbnail'
  = f.input :photos, as: :file, input_html: { multiple: true }
  = f.input :photos_cache, as: :hidden
  = f.input :price, label: 'Price ($)'

  .btn-group
    = f.button :submit, 'Add placement'
    = link_to 'Cancel', placements_path, class: 'btn btn-danger'

app/views/placements/_map.html.slim
iframe { width='100%' height='300' frameborder='0' style='border:0'
  src="https://www.google.com/maps/embed/v1/place
  ?key=#{ENV['google_maps_api']}
  &q=#{linkify_address(placement.address)}" }

app/views/placements/_search_form.html.slim
= simple_form_for :search, url: placements_path, method: :get do |f|
  = f.input :title, label: false, placeholder: 'Search for a placement title'
  .btn-group
    = f.button :submit, 'Search', class: 'btn-success'
    = f.button :submit, 'Reset'

app/views/placements/index.html.slim
.jumbotron.welcome-div
    h2 
      | Welcome to 
      span.brand-name-text Share Placement
    p 
      | On our webiste you can look for a hotel or other placement that you want
      |  to visit and read other visitors reviews about that place. 
    - if current_user
      p 
        | As a logged in user, you can add a 
        = link_to ' new placement', new_placement_path,
          data: { turbolinks: 'false' }
        |  and leave comments about other placements.
    - else 
      p 
        | You can also 
        = link_to ' Log In', login_path
        |  or
        = link_to ' Register', new_user_path
        |  to add a new placement, or to leave
        |  your comment about place that you visited.
hr

= render 'search_form'

- if @placements.empty?
  p.text-center No placements
- else
  br
  - @placements.each do |placement|
    .row.placement-container
      .col-md-7
        = link_to placement_path(placement) do
          = image_tag placement.photos.first.url, class: 'img-responsive img-rounded'
      .col-md-5
        h3 = placement.title
        p = placement_description(placement).truncate(300, separator: ' ')
        p = link_to 'More info', placement_path(placement), 
            class: 'btn btn-default'
            
= paginate @placements

app/views/placements/new.html.slim
.row
  .col-md-6.col-md-offset-3.col-sm-12
    h3 New placement
    hr
    = render 'form'

app/views/placements/show.html.slim
= link_to placements_path do
  i.fa.fa-2x.fa-arrow-left
br

h3 = @placement.title
p 
  b Address: 
  = @placement.address
p
  = render 'map', placement: @placement
p 
  b Description: 
  = placement_description(@placement)
p 
  b Price: 
  = number_to_currency(@placement.price)
p 
  b Photos: 
  - @placement.photos.each do |photo|
    br
    = image_tag photo.url,
      class: 'img-thumbnail text-center'


h2 Reviews
= render 'reviews/review', review_limit: 5
- if @placement.reviews.any?
  = link_to 'See all reviews',
    placement_reviews_path(@placement), class: 'btn btn-xs btn-default'
  

app/views/reviews/_form.html.slim
= simple_form_for [@placement, @review], html: { multipart: true } do |f|
  = f.error_notification
  
  = f.input :title
  = f.input :content
  - if @review.photos?
    - @review.photos.each do |photo|
      = image_tag photo.url, size: '50',
        class: 'img-thumbnail'
  = f.input :photos, as: :file, input_html: { multiple: true }
  = f.input :photos_cache, as: :hidden

  .btn-group
    = f.button :submit, 'Add review'
    = link_to 'Cancel', placement_path(@placement), class: 'btn btn-danger'

app/views/reviews/_review.html.slim
- if current_user  
  = link_to 'Add review', new_placement_review_path(@placement),
    class: 'btn btn-default'
hr
- if @placement.reviews.empty?
  h4.text-center No reviews
- else 
  - @placement.reviews.limit(review_limit).each do |review|            
    .review-container
      h3.review-title = review.title
      - if review.photos.any?
        = link_to 'review includes photos',
          photos_placement_review_path(@placement, review),
          class: 'btn btn-xs btn-info'
      p = review.content
      p
        b => review.user_name
        span.text-muted = review.created_at.strftime('%d-%m-%Y')

app/views/reviews/index.html.slim
= link_to placement_path(@placement) do
  i.fa.fa-2x.fa-arrow-left
br

h3 = @placement.title
= render 'reviews/review', review_limit: nil     

= paginate @reviews
    

app/views/reviews/new.html.slim
.row
  .col-md-6.col-md-offset-3.col-sm-12
    h3 = "New review for #{@placement.title}"
    hr
    = render 'form'

app/views/reviews/photos.html.slim
= link_to :back do
  i.fa.fa-2x.fa-arrow-left
br

- @photos.each do |photo|
  br
  = image_tag photo.url,
    class: 'img-thumbnail text-center'

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.error_notification

  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation

  .btn-group
    = f.button :submit, 'Sign Up'
    = link_to 'Cancel', root_path, class: 'btn btn-danger'

app/views/users/new.html.slim
.row
  .col-md-4.col-md-offset-4
    h3 Sign Up
    hr
    = render 'form'